# Generated by Django 5.1.6 on 2025-03-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Review title'),
        ),
    ]
