# Generated by Django 5.1.6 on 2025-03-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_alter_tag_options_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierecommendation',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='movierecommendation',
            name='tag',
        ),
        migrations.AddField(
            model_name='movierecommendation',
            name='tag',
            field=models.ManyToManyField(to='moviesapp.tag', verbose_name='Mood tag'),
        ),
    ]
