# Generated by Django 5.1.6 on 2025-03-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0003_alter_movierecommendation_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierecommendation',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
