# Generated by Django 5.1.6 on 2025-03-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0005_movie_rename_review_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Cover'),
        ),
        migrations.AddField(
            model_name='movierecommendation',
            name='audience',
            field=models.TextField(default=None, verbose_name='Type of viewer who would enjoy the movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movierecommendation',
            name='cherry',
            field=models.TextField(help_text='What was the standout moment for you in the movie? It could be a meaningful line of dialogue, a visually stunning scene, or a moment that resonated with you long after the movie ended', null=True, verbose_name='Cherry on top'),
        ),
        migrations.AddField(
            model_name='movierecommendation',
            name='mood',
            field=models.TextField(null=True, verbose_name='When to watch'),
        ),
    ]
