# Generated by Django 5.1.6 on 2025-03-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0006_movie_cover_movierecommendation_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierecommendation',
            name='cherry',
            field=models.TextField(blank=True, help_text='What was the standout moment for you in the movie? It could be a meaningful line of dialogue, a visually stunning scene, or a moment that resonated with you long after the movie ended', null=True, verbose_name='Cherry on top'),
        ),
        migrations.AlterField(
            model_name='movierecommendation',
            name='mood',
            field=models.TextField(blank=True, null=True, verbose_name='When to watch'),
        ),
    ]
