# Generated by Django 5.1.6 on 2025-03-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0008_alter_movie_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Synopsis'),
        ),
    ]
