# Generated by Django 5.1.6 on 2025-03-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0012_rename_synopsis_movie_overview_remove_movie_cover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='overview',
            new_name='synopsis',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_path',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_id',
        ),
        migrations.RemoveField(
            model_name='movierecommendation',
            name='trailer_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Cover'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
