# Generated by Django 5.1.6 on 2025-03-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0013_rename_overview_movie_synopsis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierecommendation',
            name='cherry',
            field=models.TextField(blank=True, null=True, verbose_name='Cherry on top'),
        ),
    ]
